In [ ]:
`

In [2]:
import pandas as pd
import statsmodels.api as sm
pd.set_option('display.max_columns', 500)

In [3]:
LinRegression = pd.read_csv('/Users/mauroaz/Downloads/home-credit-default-risk_02/new_file.csv')

In [4]:
LinRegression.shape

(307511, 139)

In [5]:

LinRegression.info(max_cols=139)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 139 columns):
SK_ID_CURR                        307511 non-null int64
TARGET                            307511 non-null int64
NAME_CONTRACT_TYPE                307511 non-null object
CODE_GENDER                       307511 non-null object
FLAG_OWN_CAR                      307511 non-null object
FLAG_OWN_REALTY                   307511 non-null object
CNT_CHILDREN                      307511 non-null int64
AMT_INCOME_TOTAL                  307511 non-null float64
AMT_CREDIT                        307511 non-null float64
AMT_ANNUITY                       307499 non-null float64
AMT_GOODS_PRICE                   307233 non-null float64
NAME_TYPE_SUITE                   306219 non-null object
NAME_INCOME_TYPE                  307511 non-null object
NAME_EDUCATION_TYPE               307511 non-null object
NAME_FAMILY_STATUS                307511 non-null object
NAME_HOUSING_TYPE                 307511 non-null object
REGION_POPULATION_RELATIVE        307511 non-null float64
DAYS_BIRTH                        307511 non-null int64
DAYS_EMPLOYED                     307511 non-null int64
DAYS_REGISTRATION                 307511 non-null float64
DAYS_ID_PUBLISH                   307511 non-null int64
OWN_CAR_AGE                       104582 non-null float64
FLAG_MOBIL                        307511 non-null int64
FLAG_EMP_PHONE                    307511 non-null int64
FLAG_WORK_PHONE                   307511 non-null int64
FLAG_CONT_MOBILE                  307511 non-null int64
FLAG_PHONE                        307511 non-null int64
FLAG_EMAIL                        307511 non-null int64
OCCUPATION_TYPE                   211120 non-null object
CNT_FAM_MEMBERS                   307509 non-null float64
REGION_RATING_CLIENT              307511 non-null int64
REGION_RATING_CLIENT_W_CITY       307511 non-null int64
WEEKDAY_APPR_PROCESS_START        307511 non-null object
HOUR_APPR_PROCESS_START           307511 non-null int64
REG_REGION_NOT_LIVE_REGION        307511 non-null int64
REG_REGION_NOT_WORK_REGION        307511 non-null int64
LIVE_REGION_NOT_WORK_REGION       307511 non-null int64
REG_CITY_NOT_LIVE_CITY            307511 non-null int64
REG_CITY_NOT_WORK_CITY            307511 non-null int64
LIVE_CITY_NOT_WORK_CITY           307511 non-null int64
ORGANIZATION_TYPE                 307511 non-null object
EXT_SOURCE_1                      134133 non-null float64
EXT_SOURCE_2                      306851 non-null float64
EXT_SOURCE_3                      246546 non-null float64
APARTMENTS_AVG                    151450 non-null float64
BASEMENTAREA_AVG                  127568 non-null float64
YEARS_BEGINEXPLUATATION_AVG       157504 non-null float64
YEARS_BUILD_AVG                   103023 non-null float64
COMMONAREA_AVG                    92646 non-null float64
ELEVATORS_AVG                     143620 non-null float64
ENTRANCES_AVG                     152683 non-null float64
FLOORSMAX_AVG                     154491 non-null float64
FLOORSMIN_AVG                     98869 non-null float64
LANDAREA_AVG                      124921 non-null float64
LIVINGAPARTMENTS_AVG              97312 non-null float64
LIVINGAREA_AVG                    153161 non-null float64
NONLIVINGAPARTMENTS_AVG           93997 non-null float64
NONLIVINGAREA_AVG                 137829 non-null float64
APARTMENTS_MODE                   151450 non-null float64
BASEMENTAREA_MODE                 127568 non-null float64
YEARS_BEGINEXPLUATATION_MODE      157504 non-null float64
YEARS_BUILD_MODE                  103023 non-null float64
COMMONAREA_MODE                   92646 non-null float64
ELEVATORS_MODE                    143620 non-null float64
ENTRANCES_MODE                    152683 non-null float64
FLOORSMAX_MODE                    154491 non-null float64
FLOORSMIN_MODE                    98869 non-null float64
LANDAREA_MODE                     124921 non-null float64
LIVINGAPARTMENTS_MODE             97312 non-null float64
LIVINGAREA_MODE                   153161 non-null float64
NONLIVINGAPARTMENTS_MODE          93997 non-null float64
NONLIVINGAREA_MODE                137829 non-null float64
APARTMENTS_MEDI                   151450 non-null float64
BASEMENTAREA_MEDI                 127568 non-null float64
YEARS_BEGINEXPLUATATION_MEDI      157504 non-null float64
YEARS_BUILD_MEDI                  103023 non-null float64
COMMONAREA_MEDI                   92646 non-null float64
ELEVATORS_MEDI                    143620 non-null float64
ENTRANCES_MEDI                    152683 non-null float64
FLOORSMAX_MEDI                    154491 non-null float64
FLOORSMIN_MEDI                    98869 non-null float64
LANDAREA_MEDI                     124921 non-null float64
LIVINGAPARTMENTS_MEDI             97312 non-null float64
LIVINGAREA_MEDI                   153161 non-null float64
NONLIVINGAPARTMENTS_MEDI          93997 non-null float64
NONLIVINGAREA_MEDI                137829 non-null float64
FONDKAPREMONT_MODE                97216 non-null object
HOUSETYPE_MODE                    153214 non-null object
TOTALAREA_MODE                    159080 non-null float64
WALLSMATERIAL_MODE                151170 non-null object
EMERGENCYSTATE_MODE               161756 non-null object
OBS_30_CNT_SOCIAL_CIRCLE          306490 non-null float64
DEF_30_CNT_SOCIAL_CIRCLE          306490 non-null float64
OBS_60_CNT_SOCIAL_CIRCLE          306490 non-null float64
DEF_60_CNT_SOCIAL_CIRCLE          306490 non-null float64
DAYS_LAST_PHONE_CHANGE            307510 non-null float64
FLAG_DOCUMENT_2                   307511 non-null int64
FLAG_DOCUMENT_3                   307511 non-null int64
FLAG_DOCUMENT_4                   307511 non-null int64
FLAG_DOCUMENT_5                   307511 non-null int64
FLAG_DOCUMENT_6                   307511 non-null int64
FLAG_DOCUMENT_7                   307511 non-null int64
FLAG_DOCUMENT_8                   307511 non-null int64
FLAG_DOCUMENT_9                   307511 non-null int64
FLAG_DOCUMENT_10                  307511 non-null int64
FLAG_DOCUMENT_11                  307511 non-null int64
FLAG_DOCUMENT_12                  307511 non-null int64
FLAG_DOCUMENT_13                  307511 non-null int64
FLAG_DOCUMENT_14                  307511 non-null int64
FLAG_DOCUMENT_15                  307511 non-null int64
FLAG_DOCUMENT_16                  307511 non-null int64
FLAG_DOCUMENT_17                  307511 non-null int64
FLAG_DOCUMENT_18                  307511 non-null int64
FLAG_DOCUMENT_19                  307511 non-null int64
FLAG_DOCUMENT_20                  307511 non-null int64
FLAG_DOCUMENT_21                  307511 non-null int64
AMT_REQ_CREDIT_BUREAU_HOUR        265992 non-null float64
AMT_REQ_CREDIT_BUREAU_DAY         265992 non-null float64
AMT_REQ_CREDIT_BUREAU_WEEK        265992 non-null float64
AMT_REQ_CREDIT_BUREAU_MON         265992 non-null float64
AMT_REQ_CREDIT_BUREAU_QRT         265992 non-null float64
AMT_REQ_CREDIT_BUREAU_YEAR        265992 non-null float64
employment_to_birth_ratio         307511 non-null float64
credit_to_annuity_ratio           307499 non-null float64
credit_to_goods_ratio             307233 non-null float64
credit_to_income_ratio            307511 non-null float64
income_credit_percentage          307511 non-null float64
income_per_child                  307511 non-null float64
income_per_person                 307509 non-null float64
payment_rate                      307499 non-null float64
no_inquiries_MON_to_birth         265992 non-null float64
no_inquiries_DAY_to_birth         265992 non-null float64
no_inquiries_WEEK_to_birth        265992 non-null float64
avg_external_source               109589 non-null float64
income_avg_external_source        109589 non-null float64
social_circle_obs_30_to_income    306490 non-null float64
social_circle_def_30_to_income    306490 non-null float64
social_circle_obs_60_to_income    306490 non-null float64
social_circle_def_60_to_income    306490 non-null float64
dtypes: float64(82), int64(41), object(16)
memory usage: 326.1+ MB

In [6]:
LinRegression.dropna(subset=['avg_external_source', 'social_circle_def_30_to_income'])

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,employment_to_birth_ratio,credit_to_annuity_ratio,credit_to_goods_ratio,credit_to_income_ratio,income_credit_percentage,income_per_child,income_per_person,payment_rate,no_inquiries_MON_to_birth,no_inquiries_DAY_to_birth,no_inquiries_WEEK_to_birth,avg_external_source,income_avg_external_source,social_circle_obs_30_to_income,social_circle_def_30_to_income,social_circle_obs_60_to_income,social_circle_def_60_to_income
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.067329,16.461104,1.158397,2.007889,0.498036,202500.000,202500.0000,0.060749,-0.000000,-0.0,-0.0,0.161787,1.251645e+06,0.000010,0.000010,0.000010,0.000010
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,1395000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.035792,-13778,-3130,-1213.0,-619,17.0,1,1,0,1,1,0,Accountants,3.0,2,2,SUNDAY,16,0,0,0,0,0,0,Business Entity Type 3,0.774761,0.724000,0.492060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-1562.0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0,0.227174,37.789061,1.118800,9.127053,0.109564,85500.000,57000.0000,0.026463,-0.000073,-0.0,-0.0,0.663607,2.576826e+05,0.000006,0.000000,0.000006,0.000006
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,-18.172198,30.142344,1.116158,9.063200,0.110336,112500.000,56250.0000,0.033176,-0.000000,-0.0,-0.0,0.514935,2.184742e+05,0.000009,0.000000,0.000009,0.000009
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,652500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.022800,-10197,-679,-4427.0,-738,NaN,1,1,0,1,0,0,Core staff,3.0,2,2,SATURDAY,15,0,0,0,0,0,0,Medicine,0.319760,0.651862,0.363945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-844.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.066588,30.811730,1.000000,5.800000,0.172414,56250.000,37500.0000,0.032455,-0.000098,-0.0,-0.0,0.445189,2.527015e+05,0.000000,0.000000,0.000000,0.000000
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,135000.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.015221,-20417,365243,-5246.0,-2512,NaN,1,0,0,1,1,0,NaN,2.0,2,2,FRIDAY,7,0,0,0,0,0,0,XNA,0.722044,0.555183,0.652897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2396.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,-17.889161,13.893805,1.099000,3.861746,0.258950,38419.155,19209.5775,0.071975,-0.000000,-0.0,-0.0,0.643375,5.971505e+04,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,225000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.007020,-16988,-8694,-5396.0,-509,NaN,1,1,1,1,1,0,Medicine staff,2.0,2,2,TUESDAY,15,0,0,0,0,0,0,Medicine,0.665343,0.649123,0.206779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.0,4.0,0.0,-1511.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0,0.511773,17.724211,1.000000,2.777778,0.360000,81000.000,40500.0000,0.056420,-0.000059,-0.0,-0.0,0.507081,1.597377e+05,0.000049,0.000000,0.000049,0.000049
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,1138500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.031329,-20390,-5326,-157.0,-3906,NaN,1,1,0,1,0,1,NaN,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.896042,0.789389,0.337673,0.1299,NaN,0.9876,NaN,NaN,0.08,0.0345,0.6250,NaN,NaN,NaN,0.1133,NaN,0.0032,0.1324,NaN,0.9876,NaN,NaN,0.0806,0.0345,0.6250,NaN,NaN,NaN,0.1179,NaN,0.0,0.1312,NaN,0.9876,NaN,NaN,0.08,0.0345,0.6250,NaN,NaN,NaN,0.1153,NaN,0.0032,NaN,block of flats,0.0890,Panel,No,0.0,0.0,0.0,0.0,-1459.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0,0.261206,36.235118,1.145202,4.995448,0.200182,261000.000,130500.0000,0.027598,-0.000049,-0.0,-0.0,0.674368,3.870291e+05,0.000000,0.000000,0.000000,0.000000
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,247500.0,Unaccompanied,Commercial associate,Higher education,Single / not married,House / apartment,0.022800,-11870,-399,-675.0,-3936,NaN,1,1,0,1,0,1,Core staff,1.0,2,2,SATURDAY,11,0,0,0,0,0,0,Bank,0.243466,0.501221,0.609276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,9.0,2.0,-2315.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0,0.033614,19.442897,1.396000,3.071200,0.325606,112500.000,112500.0000,0.051433,-0.000084,-0.0,-0.0,0.451321,2.492683e+05,0.000080,0.000027,0.000080,0.000080
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,585000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.005002,-14966,-7921,-6737.0,-5150,NaN,1,1,0,1,0,1,Managers,1.0,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.744026,0.535722,0.218859,0.1031,0.0862,0.9816,0.7484,0.0123,0.00,0.2069,0.1667,0.2083,NaN,0.0841,0.9279,0.0,0.0000,0.1050,0.0894,0.9816,0.7583,0.0124,0.0000,0.2069,0.1667,0.2083,NaN,0.0918,0.9667,0.0,0.0,0.1041,0.0862,0.9816,0.7518,0.0124,0.00,0.2069,0.1667,0.2083,NaN,0.0855,0.9445,0.0,0.0000,reg oper account,block of flats,0.7970,Panel,No,6.0,0.0,6.0,0.0,-1909.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,0.529266,22.604623,1.158400,4.429176,0.225776,153000.000,153000.0000,0.044239,-0.000067,-0.0,-0.0,0.499536,3.062844e+05,0.000039,0.000000,0.000039,0.000039
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0,0.0749,0.0526,0.9881,NaN,0.0177,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0805,NaN,0.0000,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,0.074869,13.742556,1.000000,4.285714,0.233333,157500.000,78750.0000,0.072767,-0.000119,-0.0,-0.0,0.518984,3.034778e+05,0.000000,0.000000,0.000000,0.000000

In [8]:
LinRegression
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

list(LinRegression.select_dtypes(exclude=numerics).columns)

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE']

In [10]:
LinRegression['HOUSETYPE_MODE']

0         block of flats
1         block of flats
2                    NaN
3                    NaN
4                    NaN
               ...
307506    block of flats
307507    block of flats
307508    block of flats
307509    block of flats
307510    block of flats
Name: HOUSETYPE_MODE, Length: 307511, dtype: object