In [ ]:
# Now using the NEW FEATUREs
# LinRegression = pd.read_csv('/Users/mauroaz/Downloads/home-credit-default-risk_02/new_file.csv')

In [1]:
import statsmodels.api as sm
import pandas as pd
pd.set_option('display.max_columns', 500)
#import zipfile
#with zipfile.ZipFile('../datasets/KaggleCredit2.csv.zip', 'r') as z:
 #   f = z.open('KaggleCredit2.csv')

In [2]:
LinRegression = pd.read_csv('/Users/mauroaz/Downloads/home-credit-default-risk_02/new_file.csv')

In [3]:
LinRegression.shape

(307511, 139)

In [4]:
LinRegression.dtypes

SK_ID_CURR                          int64
TARGET                              int64
NAME_CONTRACT_TYPE                 object
CODE_GENDER                        object
FLAG_OWN_CAR                       object
                                   ...
income_avg_external_source        float64
social_circle_obs_30_to_income    float64
social_circle_def_30_to_income    float64
social_circle_obs_60_to_income    float64
social_circle_def_60_to_income    float64
Length: 139, dtype: object

In [5]:
LinRegression.info(max_cols=139)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 139 columns):
SK_ID_CURR                        307511 non-null int64
TARGET                            307511 non-null int64
NAME_CONTRACT_TYPE                307511 non-null object
CODE_GENDER                       307511 non-null object
FLAG_OWN_CAR                      307511 non-null object
FLAG_OWN_REALTY                   307511 non-null object
CNT_CHILDREN                      307511 non-null int64
AMT_INCOME_TOTAL                  307511 non-null float64
AMT_CREDIT                        307511 non-null float64
AMT_ANNUITY                       307499 non-null float64
AMT_GOODS_PRICE                   307233 non-null float64
NAME_TYPE_SUITE                   306219 non-null object
NAME_INCOME_TYPE                  307511 non-null object
NAME_EDUCATION_TYPE               307511 non-null object
NAME_FAMILY_STATUS                307511 non-null object
NAME_HOUSING_TYPE                 307511 non-null object
REGION_POPULATION_RELATIVE        307511 non-null float64
DAYS_BIRTH                        307511 non-null int64
DAYS_EMPLOYED                     307511 non-null int64
DAYS_REGISTRATION                 307511 non-null float64
DAYS_ID_PUBLISH                   307511 non-null int64
OWN_CAR_AGE                       104582 non-null float64
FLAG_MOBIL                        307511 non-null int64
FLAG_EMP_PHONE                    307511 non-null int64
FLAG_WORK_PHONE                   307511 non-null int64
FLAG_CONT_MOBILE                  307511 non-null int64
FLAG_PHONE                        307511 non-null int64
FLAG_EMAIL                        307511 non-null int64
OCCUPATION_TYPE                   211120 non-null object
CNT_FAM_MEMBERS                   307509 non-null float64
REGION_RATING_CLIENT              307511 non-null int64
REGION_RATING_CLIENT_W_CITY       307511 non-null int64
WEEKDAY_APPR_PROCESS_START        307511 non-null object
HOUR_APPR_PROCESS_START           307511 non-null int64
REG_REGION_NOT_LIVE_REGION        307511 non-null int64
REG_REGION_NOT_WORK_REGION        307511 non-null int64
LIVE_REGION_NOT_WORK_REGION       307511 non-null int64
REG_CITY_NOT_LIVE_CITY            307511 non-null int64
REG_CITY_NOT_WORK_CITY            307511 non-null int64
LIVE_CITY_NOT_WORK_CITY           307511 non-null int64
ORGANIZATION_TYPE                 307511 non-null object
EXT_SOURCE_1                      134133 non-null float64
EXT_SOURCE_2                      306851 non-null float64
EXT_SOURCE_3                      246546 non-null float64
APARTMENTS_AVG                    151450 non-null float64
BASEMENTAREA_AVG                  127568 non-null float64
YEARS_BEGINEXPLUATATION_AVG       157504 non-null float64
YEARS_BUILD_AVG                   103023 non-null float64
COMMONAREA_AVG                    92646 non-null float64
ELEVATORS_AVG                     143620 non-null float64
ENTRANCES_AVG                     152683 non-null float64
FLOORSMAX_AVG                     154491 non-null float64
FLOORSMIN_AVG                     98869 non-null float64
LANDAREA_AVG                      124921 non-null float64
LIVINGAPARTMENTS_AVG              97312 non-null float64
LIVINGAREA_AVG                    153161 non-null float64
NONLIVINGAPARTMENTS_AVG           93997 non-null float64
NONLIVINGAREA_AVG                 137829 non-null float64
APARTMENTS_MODE                   151450 non-null float64
BASEMENTAREA_MODE                 127568 non-null float64
YEARS_BEGINEXPLUATATION_MODE      157504 non-null float64
YEARS_BUILD_MODE                  103023 non-null float64
COMMONAREA_MODE                   92646 non-null float64
ELEVATORS_MODE                    143620 non-null float64
ENTRANCES_MODE                    152683 non-null float64
FLOORSMAX_MODE                    154491 non-null float64
FLOORSMIN_MODE                    98869 non-null float64
LANDAREA_MODE                     124921 non-null float64
LIVINGAPARTMENTS_MODE             97312 non-null float64
LIVINGAREA_MODE                   153161 non-null float64
NONLIVINGAPARTMENTS_MODE          93997 non-null float64
NONLIVINGAREA_MODE                137829 non-null float64
APARTMENTS_MEDI                   151450 non-null float64
BASEMENTAREA_MEDI                 127568 non-null float64
YEARS_BEGINEXPLUATATION_MEDI      157504 non-null float64
YEARS_BUILD_MEDI                  103023 non-null float64
COMMONAREA_MEDI                   92646 non-null float64
ELEVATORS_MEDI                    143620 non-null float64
ENTRANCES_MEDI                    152683 non-null float64
FLOORSMAX_MEDI                    154491 non-null float64
FLOORSMIN_MEDI                    98869 non-null float64
LANDAREA_MEDI                     124921 non-null float64
LIVINGAPARTMENTS_MEDI             97312 non-null float64
LIVINGAREA_MEDI                   153161 non-null float64
NONLIVINGAPARTMENTS_MEDI          93997 non-null float64
NONLIVINGAREA_MEDI                137829 non-null float64
FONDKAPREMONT_MODE                97216 non-null object
HOUSETYPE_MODE                    153214 non-null object
TOTALAREA_MODE                    159080 non-null float64
WALLSMATERIAL_MODE                151170 non-null object
EMERGENCYSTATE_MODE               161756 non-null object
OBS_30_CNT_SOCIAL_CIRCLE          306490 non-null float64
DEF_30_CNT_SOCIAL_CIRCLE          306490 non-null float64
OBS_60_CNT_SOCIAL_CIRCLE          306490 non-null float64
DEF_60_CNT_SOCIAL_CIRCLE          306490 non-null float64
DAYS_LAST_PHONE_CHANGE            307510 non-null float64
FLAG_DOCUMENT_2                   307511 non-null int64
FLAG_DOCUMENT_3                   307511 non-null int64
FLAG_DOCUMENT_4                   307511 non-null int64
FLAG_DOCUMENT_5                   307511 non-null int64
FLAG_DOCUMENT_6                   307511 non-null int64
FLAG_DOCUMENT_7                   307511 non-null int64
FLAG_DOCUMENT_8                   307511 non-null int64
FLAG_DOCUMENT_9                   307511 non-null int64
FLAG_DOCUMENT_10                  307511 non-null int64
FLAG_DOCUMENT_11                  307511 non-null int64
FLAG_DOCUMENT_12                  307511 non-null int64
FLAG_DOCUMENT_13                  307511 non-null int64
FLAG_DOCUMENT_14                  307511 non-null int64
FLAG_DOCUMENT_15                  307511 non-null int64
FLAG_DOCUMENT_16                  307511 non-null int64
FLAG_DOCUMENT_17                  307511 non-null int64
FLAG_DOCUMENT_18                  307511 non-null int64
FLAG_DOCUMENT_19                  307511 non-null int64
FLAG_DOCUMENT_20                  307511 non-null int64
FLAG_DOCUMENT_21                  307511 non-null int64
AMT_REQ_CREDIT_BUREAU_HOUR        265992 non-null float64
AMT_REQ_CREDIT_BUREAU_DAY         265992 non-null float64
AMT_REQ_CREDIT_BUREAU_WEEK        265992 non-null float64
AMT_REQ_CREDIT_BUREAU_MON         265992 non-null float64
AMT_REQ_CREDIT_BUREAU_QRT         265992 non-null float64
AMT_REQ_CREDIT_BUREAU_YEAR        265992 non-null float64
employment_to_birth_ratio         307511 non-null float64
credit_to_annuity_ratio           307499 non-null float64
credit_to_goods_ratio             307233 non-null float64
credit_to_income_ratio            307511 non-null float64
income_credit_percentage          307511 non-null float64
income_per_child                  307511 non-null float64
income_per_person                 307509 non-null float64
payment_rate                      307499 non-null float64
no_inquiries_MON_to_birth         265992 non-null float64
no_inquiries_DAY_to_birth         265992 non-null float64
no_inquiries_WEEK_to_birth        265992 non-null float64
avg_external_source               109589 non-null float64
income_avg_external_source        109589 non-null float64
social_circle_obs_30_to_income    306490 non-null float64
social_circle_def_30_to_income    306490 non-null float64
social_circle_obs_60_to_income    306490 non-null float64
social_circle_def_60_to_income    306490 non-null float64
dtypes: float64(82), int64(41), object(16)
memory usage: 326.1+ MB

In [7]:
# Dril Down to check for: Float, Integer, Categorical
LinRegression['TARGET']
# The dependant VARIABLE has to be "binary" ???? or ????

0         1
1         0
2         0
3         0
4         0
         ..
307506    0
307507    0
307508    0
307509    1
307510    0
Name: TARGET, Length: 307511, dtype: int64

In [40]:
# Dril Down to check for: Float, Integer, Categorical
#LinRegression['DAYS_BIRTH']

In [12]:
# Dril Down to check for: Float, 
LinRegression

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

list(LinRegression.select_dtypes(include=numerics).columns)

['SK_ID_CURR',
 'TARGET',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'TOTALAREA_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR',
 'employment_to_birth_ratio',
 'credit_to_annuity_ratio',
 'credit_to_goods_ratio',
 'credit_to_income_ratio',
 'income_credit_percentage',
 'income_per_child',
 'income_per_person',
 'payment_rate',
 'no_inquiries_MON_to_birth',
 'no_inquiries_DAY_to_birth',
 'no_inquiries_WEEK_to_birth',
 'avg_external_source',
 'income_avg_external_source',
 'social_circle_obs_30_to_income',
 'social_circle_def_30_to_income',
 'social_circle_obs_60_to_income',
 'social_circle_def_60_to_income']

In [19]:
LinRegression.shape

(307511, 139)

In [20]:
#Checking for NULLS
pd.options.display.max_rows = 139
LinRegression.isnull().sum()

SK_ID_CURR                             0
TARGET                                 0
NAME_CONTRACT_TYPE                     0
CODE_GENDER                            0
FLAG_OWN_CAR                           0
FLAG_OWN_REALTY                        0
CNT_CHILDREN                           0
AMT_INCOME_TOTAL                       0
AMT_CREDIT                             0
AMT_ANNUITY                           12
AMT_GOODS_PRICE                      278
NAME_TYPE_SUITE                     1292
NAME_INCOME_TYPE                       0
NAME_EDUCATION_TYPE                    0
NAME_FAMILY_STATUS                     0
NAME_HOUSING_TYPE                      0
REGION_POPULATION_RELATIVE             0
DAYS_BIRTH                             0
DAYS_EMPLOYED                          0
DAYS_REGISTRATION                      0
DAYS_ID_PUBLISH                        0
OWN_CAR_AGE                       202929
FLAG_MOBIL                             0
FLAG_EMP_PHONE                         0
FLAG_WORK_PHONE                        0
FLAG_CONT_MOBILE                       0
FLAG_PHONE                             0
FLAG_EMAIL                             0
OCCUPATION_TYPE                    96391
CNT_FAM_MEMBERS                        2
REGION_RATING_CLIENT                   0
REGION_RATING_CLIENT_W_CITY            0
WEEKDAY_APPR_PROCESS_START             0
HOUR_APPR_PROCESS_START                0
REG_REGION_NOT_LIVE_REGION             0
REG_REGION_NOT_WORK_REGION             0
LIVE_REGION_NOT_WORK_REGION            0
REG_CITY_NOT_LIVE_CITY                 0
REG_CITY_NOT_WORK_CITY                 0
LIVE_CITY_NOT_WORK_CITY                0
ORGANIZATION_TYPE                      0
EXT_SOURCE_1                      173378
EXT_SOURCE_2                         660
EXT_SOURCE_3                       60965
APARTMENTS_AVG                    156061
BASEMENTAREA_AVG                  179943
YEARS_BEGINEXPLUATATION_AVG       150007
YEARS_BUILD_AVG                   204488
COMMONAREA_AVG                    214865
ELEVATORS_AVG                     163891
ENTRANCES_AVG                     154828
FLOORSMAX_AVG                     153020
FLOORSMIN_AVG                     208642
LANDAREA_AVG                      182590
LIVINGAPARTMENTS_AVG              210199
LIVINGAREA_AVG                    154350
NONLIVINGAPARTMENTS_AVG           213514
NONLIVINGAREA_AVG                 169682
APARTMENTS_MODE                   156061
BASEMENTAREA_MODE                 179943
YEARS_BEGINEXPLUATATION_MODE      150007
YEARS_BUILD_MODE                  204488
COMMONAREA_MODE                   214865
ELEVATORS_MODE                    163891
ENTRANCES_MODE                    154828
FLOORSMAX_MODE                    153020
FLOORSMIN_MODE                    208642
LANDAREA_MODE                     182590
LIVINGAPARTMENTS_MODE             210199
LIVINGAREA_MODE                   154350
NONLIVINGAPARTMENTS_MODE          213514
NONLIVINGAREA_MODE                169682
APARTMENTS_MEDI                   156061
BASEMENTAREA_MEDI                 179943
YEARS_BEGINEXPLUATATION_MEDI      150007
YEARS_BUILD_MEDI                  204488
COMMONAREA_MEDI                   214865
ELEVATORS_MEDI                    163891
ENTRANCES_MEDI                    154828
FLOORSMAX_MEDI                    153020
FLOORSMIN_MEDI                    208642
LANDAREA_MEDI                     182590
LIVINGAPARTMENTS_MEDI             210199
LIVINGAREA_MEDI                   154350
NONLIVINGAPARTMENTS_MEDI          213514
NONLIVINGAREA_MEDI                169682
FONDKAPREMONT_MODE                210295
HOUSETYPE_MODE                    154297
TOTALAREA_MODE                    148431
WALLSMATERIAL_MODE                156341
EMERGENCYSTATE_MODE               145755
OBS_30_CNT_SOCIAL_CIRCLE            1021
DEF_30_CNT_SOCIAL_CIRCLE            1021
OBS_60_CNT_SOCIAL_CIRCLE            1021
DEF_60_CNT_SOCIAL_CIRCLE            1021
DAYS_LAST_PHONE_CHANGE                 1
FLAG_DOCUMENT_2                        0
FLAG_DOCUMENT_3                        0
FLAG_DOCUMENT_4                        0
FLAG_DOCUMENT_5                        0
FLAG_DOCUMENT_6                        0
FLAG_DOCUMENT_7                        0
FLAG_DOCUMENT_8                        0
FLAG_DOCUMENT_9                        0
FLAG_DOCUMENT_10                       0
FLAG_DOCUMENT_11                       0
FLAG_DOCUMENT_12                       0
FLAG_DOCUMENT_13                       0
FLAG_DOCUMENT_14                       0
FLAG_DOCUMENT_15                       0
FLAG_DOCUMENT_16                       0
FLAG_DOCUMENT_17                       0
FLAG_DOCUMENT_18                       0
FLAG_DOCUMENT_19                       0
FLAG_DOCUMENT_20                       0
FLAG_DOCUMENT_21                       0
AMT_REQ_CREDIT_BUREAU_HOUR         41519
AMT_REQ_CREDIT_BUREAU_DAY          41519
AMT_REQ_CREDIT_BUREAU_WEEK         41519
AMT_REQ_CREDIT_BUREAU_MON          41519
AMT_REQ_CREDIT_BUREAU_QRT          41519
AMT_REQ_CREDIT_BUREAU_YEAR         41519
employment_to_birth_ratio              0
credit_to_annuity_ratio               12
credit_to_goods_ratio                278
credit_to_income_ratio                 0
income_credit_percentage               0
income_per_child                       0
income_per_person                      2
payment_rate                          12
no_inquiries_MON_to_birth          41519
no_inquiries_DAY_to_birth          41519
no_inquiries_WEEK_to_birth         41519
avg_external_source               197922
income_avg_external_source        197922
social_circle_obs_30_to_income      1021
social_circle_def_30_to_income      1021
social_circle_obs_60_to_income      1021
social_circle_def_60_to_income      1021
dtype: int64

In [26]:
# Now I know wher e the NULLS are... 
# Lets find the NULLS columns
#LinRegression['AMT_REQ_CREDIT_BUREAU_HOUR'].head
tha

In [ ]:
##DROP the Nulls  ALL THE NULLS
#LinRegression.dropna(inplace=True)
#LinRegression.shape

In [ ]:
## DROP ROWS some Nulls by PICKING THEM
##df.dropna(subset=['', ''])

In [27]:
LinRegression.dropna(subset=['avg_external_source', 'social_circle_def_30_to_income'])

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,employment_to_birth_ratio,credit_to_annuity_ratio,credit_to_goods_ratio,credit_to_income_ratio,income_credit_percentage,income_per_child,income_per_person,payment_rate,no_inquiries_MON_to_birth,no_inquiries_DAY_to_birth,no_inquiries_WEEK_to_birth,avg_external_source,income_avg_external_source,social_circle_obs_30_to_income,social_circle_def_30_to_income,social_circle_obs_60_to_income,social_circle_def_60_to_income
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.067329,16.461104,1.158397,2.007889,0.498036,202500.000,202500.0000,0.060749,-0.000000,-0.0,-0.0,0.161787,1.251645e+06,0.000010,0.000010,0.000010,0.000010
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,1395000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.035792,-13778,-3130,-1213.0,-619,17.0,1,1,0,1,1,0,Accountants,3.0,2,2,SUNDAY,16,0,0,0,0,0,0,Business Entity Type 3,0.774761,0.724000,0.492060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,-1562.0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0,0.227174,37.789061,1.118800,9.127053,0.109564,85500.000,57000.0000,0.026463,-0.000073,-0.0,-0.0,0.663607,2.576826e+05,0.000006,0.000000,0.000006,0.000006
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,-18.172198,30.142344,1.116158,9.063200,0.110336,112500.000,56250.0000,0.033176,-0.000000,-0.0,-0.0,0.514935,2.184742e+05,0.000009,0.000000,0.000009,0.000009
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,652500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.022800,-10197,-679,-4427.0,-738,NaN,1,1,0,1,0,0,Core staff,3.0,2,2,SATURDAY,15,0,0,0,0,0,0,Medicine,0.319760,0.651862,0.363945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-844.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.066588,30.811730,1.000000,5.800000,0.172414,56250.000,37500.0000,0.032455,-0.000098,-0.0,-0.0,0.445189,2.527015e+05,0.000000,0.000000,0.000000,0.000000
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,135000.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.015221,-20417,365243,-5246.0,-2512,NaN,1,0,0,1,1,0,NaN,2.0,2,2,FRIDAY,7,0,0,0,0,0,0,XNA,0.722044,0.555183,0.652897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-2396.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,-17.889161,13.893805,1.099000,3.861746,0.258950,38419.155,19209.5775,0.071975,-0.000000,-0.0,-0.0,0.643375,5.971505e+04,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,225000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.007020,-16988,-8694,-5396.0,-509,NaN,1,1,1,1,1,0,Medicine staff,2.0,2,2,TUESDAY,15,0,0,0,0,0,0,Medicine,0.665343,0.649123,0.206779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.0,4.0,0.0,-1511.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0,0.511773,17.724211,1.000000,2.777778,0.360000,81000.000,40500.0000,0.056420,-0.000059,-0.0,-0.0,0.507081,1.597377e+05,0.000049,0.000000,0.000049,0.000049
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,1138500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.031329,-20390,-5326,-157.0,-3906,NaN,1,1,0,1,0,1,NaN,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.896042,0.789389,0.337673,0.1299,NaN,0.9876,NaN,NaN,0.08,0.0345,0.6250,NaN,NaN,NaN,0.1133,NaN,0.0032,0.1324,NaN,0.9876,NaN,NaN,0.0806,0.0345,0.6250,NaN,NaN,NaN,0.1179,NaN,0.0,0.1312,NaN,0.9876,NaN,NaN,0.08,0.0345,0.6250,NaN,NaN,NaN,0.1153,NaN,0.0032,NaN,block of flats,0.0890,Panel,No,0.0,0.0,0.0,0.0,-1459.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0,0.261206,36.235118,1.145202,4.995448,0.200182,261000.000,130500.0000,0.027598,-0.000049,-0.0,-0.0,0.674368,3.870291e+05,0.000000,0.000000,0.000000,0.000000
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,247500.0,Unaccompanied,Commercial associate,Higher education,Single / not married,House / apartment,0.022800,-11870,-399,-675.0,-3936,NaN,1,1,0,1,0,1,Core staff,1.0,2,2,SATURDAY,11,0,0,0,0,0,0,Bank,0.243466,0.501221,0.609276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,3.0,9.0,2.0,-2315.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0,0.033614,19.442897,1.396000,3.071200,0.325606,112500.000,112500.0000,0.051433,-0.000084,-0.0,-0.0,0.451321,2.492683e+05,0.000080,0.000027,0.000080,0.000080
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,585000.0,Unaccompanied,Working,Higher education,Separated,House / apartment,0.005002,-14966,-7921,-6737.0,-5150,NaN,1,1,0,1,0,1,Managers,1.0,3,3,THURSDAY,9,0,0,0,0,1,1,School,0.744026,0.535722,0.218859,0.1031,0.0862,0.9816,0.7484,0.0123,0.00,0.2069,0.1667,0.2083,NaN,0.0841,0.9279,0.0,0.0000,0.1050,0.0894,0.9816,0.7583,0.0124,0.0000,0.2069,0.1667,0.2083,NaN,0.0918,0.9667,0.0,0.0,0.1041,0.0862,0.9816,0.7518,0.0124,0.00,0.2069,0.1667,0.2083,NaN,0.0855,0.9445,0.0,0.0000,reg oper account,block of flats,0.7970,Panel,No,6.0,0.0,6.0,0.0,-1909.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,0.529266,22.604623,1.158400,4.429176,0.225776,153000.000,153000.0000,0.044239,-0.000067,-0.0,-0.0,0.499536,3.062844e+05,0.000039,0.000000,0.000039,0.000039
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,675000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,Laborers,2.0,1,1,THURSDAY,20,0,0,0,0,1,1,Business Entity Type 3,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0,0.0749,0.0526,0.9881,NaN,0.0177,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0805,NaN,0.0000,NaN,block of flats,0.0718,Panel,No,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,0.074869,13.742556,1.000000,4.285714,0.233333,157500.000,78750.0000,0.072767,-0.000119,-0.0,-0.0,0.518984,3.034778e+05,0.000000,0.000000,0.000000,0.000000

In [31]:
# TO Keep the results lets redefine it
LinReg_without_Nulls = LinRegression.dropna(subset=[ 'social_circle_def_30_to_income'])

In [28]:
LinRegression.shape

(307511, 139)

In [ ]:
# after dropping the rows....

In [36]:
LinReg_without_Nulls.shape

(306490, 139)

In [ ]:
## drop columns with to many NULLS

In [33]:
# Dril Down to check for: Categoricals ==> (Python cannot recognize DATATYPE 'objects' ) 
LinRegression

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

list(LinRegression.select_dtypes(exclude=numerics).columns)

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE']

In [41]:
LinReg_without_Nulls

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

list(LinReg_without_Nulls.select_dtypes(exclude=numerics).columns)

['NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'OCCUPATION_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'ORGANIZATION_TYPE',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE']

In [43]:
#now double check to see if they REAL are categorical
LinReg_without_Nulls['HOUSETYPE_MODE']

0         block of flats
1         block of flats
2                    NaN
3                    NaN
4                    NaN
               ...
307506    block of flats
307507    block of flats
307508    block of flats
307509    block of flats
307510    block of flats
Name: HOUSETYPE_MODE, Length: 306490, dtype: object

In [ ]:
LinReg_without_Nulls

In [ ]:
df.loc[:, df.dtypes == object].apply(pd.Series.nunique)

In [37]:
LinRegression.select_dtypes(include=['float64', 'int64'])

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,employment_to_birth_ratio,credit_to_annuity_ratio,credit_to_goods_ratio,credit_to_income_ratio,income_credit_percentage,income_per_child,income_per_person,payment_rate,no_inquiries_MON_to_birth,no_inquiries_DAY_to_birth,no_inquiries_WEEK_to_birth,avg_external_source,income_avg_external_source,social_circle_obs_30_to_income,social_circle_def_30_to_income,social_circle_obs_60_to_income,social_circle_def_60_to_income
0,100002,1,0,202500.0,406597.5,24700.5,351000.0,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,1.0,2,2,10,0,0,0,0,0,0,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0,0.0000,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.0000,0.0149,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.067329,16.461104,1.158397,2.007889,0.498036,202500.0,202500.0,0.060749,-0.000000,-0.0,-0.0,0.161787,1.251645e+06,0.000010,0.00001,0.000010,0.000010
1,100003,0,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,2.0,1,1,11,0,0,0,0,0,0,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0,0.0000,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,0.0714,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.070862,36.234085,1.145199,4.790750,0.208736,270000.0,135000.0,0.027598,-0.000000,-0.0,-0.0,NaN,NaN,0.000004,0.00000,0.000004,0.000004
2,100004,0,0,67500.0,135000.0,6750.0,135000.0,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,1.0,2,2,9,0,0,0,0,0,0,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.011814,20.000000,1.000000,2.000000,0.500000,67500.0,67500.0,0.050000,-0.000000,-0.0,-0.0,NaN,NaN,0.000000,0.00000,0.000000,0.000000
3,100006,0,0,135000.0,312682.5,29686.5,297000.0,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,2.0,2,2,17,0,0,0,0,0,0,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.159905,10.532818,1.052803,2.316167,0.431748,135000.0,67500.0,0.094941,NaN,NaN,NaN,NaN,NaN,0.000015,0.00000,0.000015,0.000015
4,100007,0,0,121500.0,513000.0,21865.5,513000.0,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,1.0,2,2,11,0,0,0,0,1,1,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.152418,23.461618,1.000000,4.222222,0.236842,121500.0,121500.0,0.042623,-0.000000,-0.0,-0.0,NaN,NaN,0.000000,0.00000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,0,157500.0,254700.0,27558.0,225000.0,0.032561,-9327,-236,-8456.0,-1982,NaN,1,1,0,1,0,0,1.0,1,1,15,0,0,0,0,0,0,0.145570,0.681632,NaN,0.2021,0.0887,0.9876,0.8300,0.0202,0.22,0.1034,0.6042,0.2708,0.0594,0.1484,0.1965,0.0753,0.1095,0.1008,0.0172,0.9782,0.7125,0.0172,0.0806,0.0345,0.4583,0.0417,0.0094,0.0882,0.0853,0.0,0.0125,0.2040,0.0887,0.9876,0.8323,0.0203,0.22,0.1034,0.6042,0.2708,0.0605,0.1509,0.2001,0.0757,0.1118,0.2898,0.0,0.0,0.0,0.0,-273.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.025303,9.242325,1.132000,1.617143,0.618375,157500.0,157500.0,0.108198,NaN,NaN,NaN,NaN,NaN,0.000000,0.00000,0.000000,0.000000
307507,456252,0,0,72000.0,269550.0,12001.5,225000.0,0.025164,-20775,365243,-4388.0,-4090,NaN,1,0,0,1,1,0,1.0,2,2,8,0,0,0,0,0,0,NaN,0.115992,NaN,0.0247,0.0435,0.9727,0.6260,0.0022,0.00,0.1034,0.0833,0.1250,0.0579,0.0202,0.0257,0.0000,0.0000,0.0252,0.0451,0.9727,0.6406,0.0022,0.0000,0.1034,0.0833,0.1250,0.0592,0.0220,0.0267,0.0,0.0000,0.0250,0.0435,0.9727,0.6310,0.0022,0.00,0.1034,0.0833,0.1250,0.0589,0.0205,0.0261,0.0000,0.0000,0.0214,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,-17.580890,22.459693,1.198000,3.743750,0.267112,72000.0,72000.0,0.044524,NaN,NaN,NaN,NaN,NaN,0.000000,0.00000,0.000000,0.000000
307508,456253,0,0,153000.0,677664.0,29979.0,585000.0,0.005002,-14966,-7921,-6737.0,-5150,NaN,1,1,0,1,0,1,1.0,3,3,9,0,0,0,0,1,1,0.744026,0.535722,0.218859,0.1031,0.0862,0.9816,0.7484,0.0123,0.00,0.2069,0.1667,0.2083,NaN,0.0841,0.9279,0.0000,0.0000,0.1050,0.0894,0.9816,0.7583,0.0124,0.0000,0.2069,0.1667,0.2083,NaN,0.0918,0.9667,0.0,0.0000,0.1041,0.0862,0.9816,0.7518,0.0124,0.00,0.2069,0.1667,0.2083,NaN,0.0855,0.9445,0.0000,0.0000,0.7970,6.0,0.0,6.0,0.0,-1909.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,0.529266,22.604623,1.158400,4.429176,0.225776,153000.0,153000.0,0.044239,-0.000067,-0.0,-0.0,0.499536,3.062844e+05,0.000039,0.00000,0.000039,0.000039
307509,456254,1,0,171000.0,370107.0,20205.0,319500.0,0.005313,-11961,-4786,-2562.0,-931,NaN,1,1,0,1,0,0,2.0,2,2,9,0,0,0,1,1,0,NaN,0.514163,0.661024,0.0124,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0061,NaN,NaN,0.0126,NaN,0.9772,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0063,NaN,NaN,0.0125,NaN,0.9771,NaN,NaN,NaN,0.0690,0.0417,NaN,NaN,NaN,0.0062,NaN,NaN,0.0086,0.0,0.0,0.0,0.0,-322.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.400134,18.317595,1.158394,2.164368,0.462029,171000.0,85500.0,0.054592,-0.000000,-0.0,-0.0,NaN,NaN,0.000000,0.00000,0.000000,0.000000
307510,456255,0,0,157500.0,675000.0,49117.5,675000.0,0.046220,-16856,-1262,-5128.0,-410,NaN,1,1,1,1,1,0,2.0,1,1,20,0,0,0,0,1,1,0.734460,0.708569,0.113922,0.0742,0.0526,0.9881,NaN,0.0176,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0791,NaN,0.0000,0.0756,0.0546,0.9881,NaN,0.0178,0.0806,0.0690,0.3750,NaN,NaN,NaN,0.0824,NaN,0.0000,0.0749,0.0526,0.9881,NaN,0.0177,0.08,0.0690,0.3750,NaN,NaN,NaN,0.0805,NaN,0.0000,0.0718,0.0,0.0,0.0,0.0,-787.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,0.074869,13.742556,1.000000,4.285714,0.233333,157500.0,78750.0,0.072767,-0.000119,-0.0,-0.0,0.518984,3.034778e+05,0.000000,0.00000,0.000000,0.000000

In [38]:
## ???? What is this :::: hihihih :-)
import numpy as np
LinRegression = pd.DataFrame({ 'id': [1,2,3], 'c1':[0,0,np.nan], 'c2': [np.nan,1,1]})
LinRegression = LinRegression[['id', 'c1', 'c2']]
LinRegression['num_nulls'] = LinRegression[['c1', 'c2']].isnull().sum(axis=1)
LinRegression.head()

   id   c1   c2  num_nulls
0   1  0.0  NaN          1
1   2  0.0  1.0          0
2   3  NaN  1.0          1

In [ ]:
## LinRegression.info(max_cols=139)

## Dril Down to check for: Float,

In [44]:
# Dril Down to check for: Float, 
LinReg_without_Nulls
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

list(LinReg_without_Nulls.select_dtypes(include=numerics).columns)

['SK_ID_CURR',
 'TARGET',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'TOTALAREA_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR',
 'employment_to_birth_ratio',
 'credit_to_annuity_ratio',
 'credit_to_goods_ratio',
 'credit_to_income_ratio',
 'income_credit_percentage',
 'income_per_child',
 'income_per_person',
 'payment_rate',
 'no_inquiries_MON_to_birth',
 'no_inquiries_DAY_to_birth',
 'no_inquiries_WEEK_to_birth',
 'avg_external_source',
 'income_avg_external_source',
 'social_circle_obs_30_to_income',
 'social_circle_def_30_to_income',
 'social_circle_obs_60_to_income',
 'social_circle_def_60_to_income']

The FEATURES to KEEP are the ones with  'P>|t|' of 0.05 or less

In [ ]:
LinReg_without_Nulls

In [48]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
## categorical variable NEEDs to be wraped in :::c()::::
linreg = smf.ols(formula='TARGET ~ AMT_CREDIT + payment_rate + AMT_INCOME_TOTAL + C(CODE_GENDER) + C(FLAG_OWN_CAR) ', data=LinReg_without_Nulls).fit()

In [49]:
linreg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 TARGET   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     293.3
Date:                Tue, 07 Jan 2020   Prob (F-statistic):               0.00
Time:                        19:43:25   Log-Likelihood:                -35714.
No. Observations:              306478   AIC:                         7.144e+04
Df Residuals:                  306471   BIC:                         7.152e+04
Df Model:                           6
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 0.0962      0.002     45.616      0.000       0.092       0.100
C(CODE_GENDER)[T.M]       0.0409      0.001     36.900      0.000       0.039       0.043
C(CODE_GENDER)[T.XNA]    -0.0680      0.136     -0.500      0.617      -0.334       0.198
C(FLAG_OWN_CAR)[T.Y]     -0.0246      0.001    -22.037      0.000      -0.027      -0.022
AMT_CREDIT            -2.251e-08   1.51e-09    -14.942      0.000   -2.55e-08   -1.96e-08
payment_rate             -0.1374      0.027     -5.179      0.000      -0.189      -0.085
AMT_INCOME_TOTAL       -6.71e-10   2.11e-09     -0.318      0.750    -4.8e-09    3.46e-09
==============================================================================
Omnibus:                   184226.116   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1168016.978
Skew:                           3.048   Prob(JB):                         0.00
Kurtosis:                      10.369   Cond. No.                     2.05e+08
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.05e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
CODE_GENDER

## Let's try SKLEARN

In [ ]:
from sklearn.linear_model import LogisticRegression

Logit = LogisticRegression(n_jobs=-1)
Logit.fit(X_train, y_train)